import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const AUDIO_FILE = path.join(__dirname, '..', 'public', 'demo-audio2.mp3');

async function transcribeWithAssemblyAI() {
  const apiKey = process.env.AssemblyAI_KEY || process.env.VITE_SPEECH_API_KEY;
  if (!apiKey) throw new Error('AssemblyAI API key not found in env');

  console.log('Uploading audio to AssemblyAI...');
  const audioData = fs.readFileSync(AUDIO_FILE);

  const uploadRes = await fetch('https://api.assemblyai.com/v2/upload', {
    method: 'POST',
    headers: { authorization: apiKey },
    body: audioData,
  });
  if (!uploadRes.ok) throw new Error(`Upload failed: ${uploadRes.statusText}`);
  const { upload_url } = await uploadRes.json();

  console.log('Transcribing...');
  const transcriptRes = await fetch('https://api.assemblyai.com/v2/transcript', {
    method: 'POST',
    headers: {
      authorization: apiKey,
      'content-type': 'application/json',
    },
    body: JSON.stringify({ audio_url: upload_url, language_code: 'en' }),
  });
  if (!transcriptRes.ok) throw new Error(`Transcription request failed: ${transcriptRes.statusText}`);
  const { id } = await transcriptRes.json();

  // Poll for completion
  while (true) {
    const pollRes = await fetch(`https://api.assemblyai.com/v2/transcript/${id}`, {
      headers: { authorization: apiKey },
    });
    const result = await pollRes.json();
    if (result.status === 'completed') {
      console.log(`Transcription complete (confidence: ${result.confidence})`);
      return { transcription: result.text, confidence: result.confidence };
    }
    if (result.status === 'error') throw new Error(`Transcription error: ${result.error}`);
    console.log(`Status: ${result.status}... waiting`);
    await new Promise(r => setTimeout(r, 3000));
  }
}

async function analyzeWithOpenAI(transcription) {
  const apiKey = process.env.OPENAI_API_KEY;
  const model = process.env.OPENAI_MODEL || 'gpt-4-turbo-preview';
  if (!apiKey) throw new Error('OPENAI_API_KEY not found in env');

  console.log(`Analyzing with OpenAI (${model})...`);

  const prompt = `Analyze this senior living conversation transcript and extract structured insights.

Transcript:
${transcription}

Extract the following and return ONLY valid JSON:
{
  "formData": {
    "situation": "phone-call" or "tour" or "walk-in" (pick best fit),
    "firstName": "prospect first name",
    "lastName": "prospect last name",
    "phone": "phone if mentioned or realistic placeholder",
    "email": "email if mentioned or realistic placeholder",
    "zipcode": "zipcode if mentioned or realistic placeholder"
  },
  "keyPoints": ["array of 4-5 key discussion points"],
  "concerns": ["array of 3-4 concerns raised"],
  "smallThings": ["array of 4-5 small personal details mentioned"],
  "decisionMakers": ["array of decision makers involved"],
  "budget": ["array of budget/financial details mentioned"],
  "careLevel": ["array of care level details discussed"]
}`;

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      model,
      messages: [
        { role: 'system', content: 'You analyze senior living tour/call conversations. Always respond with valid JSON only.' },
        { role: 'user', content: prompt },
      ],
      temperature: 0.5,
      response_format: { type: 'json_object' },
    }),
  });

  if (!response.ok) {
    const err = await response.text();
    throw new Error(`OpenAI API error: ${response.statusText} - ${err}`);
  }

  const data = await response.json();
  return JSON.parse(data.choices[0].message.content);
}

async function main() {
  if (!fs.existsSync(AUDIO_FILE)) {
    throw new Error(`Audio file not found: ${AUDIO_FILE}`);
  }

  const { transcription, confidence } = await transcribeWithAssemblyAI();
  const analysis = await analyzeWithOpenAI(transcription);

  const mockDataContent = `/**
 * Mock data for Audio Sample demo flow
 * Generated by scripts/generateAudioSampleMock.js
 *
 * This data simulates what would be returned from:
 * 1. Speech-to-text transcription of demo-audio2.mp3
 * 2. AI analysis of the transcription
 */

export const audioSampleMockData = {
  // Pre-filled form data
  formData: ${JSON.stringify(analysis.formData, null, 4).replace(/\n/g, '\n    ').replace(/^{/, '{').trimEnd()},

  // Transcription result
  recordingData: {
    transcription: ${JSON.stringify(transcription)},
    confidence: ${confidence},
    provider: 'assemblyai',
    // Audio blob will be loaded from /demo-audio2.mp3
  },

  // AI analysis result
  summaryData: {
    keyPoints: ${JSON.stringify(analysis.keyPoints, null, 4)},
    concerns: ${JSON.stringify(analysis.concerns, null, 4)},
    smallThings: ${JSON.stringify(analysis.smallThings, null, 4)},
    decisionMakers: ${JSON.stringify(analysis.decisionMakers, null, 4)},
    budget: ${JSON.stringify(analysis.budget, null, 4)},
    careLevel: ${JSON.stringify(analysis.careLevel, null, 4)},
    transcription: ${JSON.stringify(transcription)}
  }
};
`;

  const outputPath = path.join(__dirname, '..', 'src', 'data', 'mockAudioSampleData.js');
  fs.writeFileSync(outputPath, mockDataContent);
  console.log(`\nMock data written to ${outputPath}`);
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
